version: "3.9"
services:
  db:
    image: mysql:8.0.43  # 稳定版，需 9.1 可替换为 mysql:9.1.0
    container_name: financialproject-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hzy200804  # root 用户密码
      MYSQL_DATABASE: projectdb       # 自动创建的数据库名
      # MYSQL_USER: dev                 # 应用专用用户
      # MYSQL_PASSWORD: devproject      # 应用用户密码
    ports:
      - "13306:3306"  # 宿主机:容器端口映射
    volumes:
      - mysql_proj_data:/var/lib/mysql  # 持久化数据卷
      - ./sql:/docker-entrypoint-initdb.d  # 初始化 SQL 脚本目录

volumes:
  mysql_proj_data:  # 声明数据卷（自动创建）